In [2]:
from rich import print
print("reck98")

reck98

In [3]:
import torch

print(torch.__version__)

if torch.cuda.is_available():
    print(f"Device Name: {torch.cuda.get_device_name(0)}")
    print(f"Device Memory: {torch.cuda.mem_get_info(0)}")
    print(f"VRAM available : {round((torch.cuda.get_device_properties(0).total_memory / (1024 * 1024 * 1024)), 2)}")
    

2.5.1+cu121

Device Name: NVIDIA GeForce RTX 2050

Device Memory: (3464757248, 4294508544)

VRAM available : 4.0

In [4]:
a = torch.empty(5, 3)
print(type(a))

<class 'torch.Tensor'>

In [5]:
print(torch.rand(5, 3))

tensor([[0.0358, 0.8397, 0.7691],
        [0.7973, 0.5798, 0.3541],
        [0.3063, 0.2608, 0.0053],
        [0.2679, 0.4234, 0.4822],
        [0.3489, 0.5835, 0.3744]])

In [6]:
## using seed 

print(torch.manual_seed(42))
print(torch.rand(5,3))


<torch._C.Generator object at 0x000001DFFF330570>

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

In [7]:

print(torch.manual_seed(42))
print(torch.rand(5,3))

<torch._C.Generator object at 0x000001DFFF330570>

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

In [8]:
X = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

In [9]:
print(X)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
X = torch.full(
    size=(4,3,2), 
    fill_value=23, 
    dtype=torch.float32
)

In [11]:
X


tensor([[[23., 23.],
         [23., 23.],
         [23., 23.]],

        [[23., 23.],
         [23., 23.],
         [23., 23.]],

        [[23., 23.],
         [23., 23.],
         [23., 23.]],

        [[23., 23.],
         [23., 23.],
         [23., 23.]]])

In [12]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [13]:
print(device)

cuda

In [14]:
R = torch.rand(2,3).to(device)

## check whether the tensor is on GPU or not

print(R.is_cuda)

True

In [15]:
X = torch.zeros(2,3, device=device)

print(X.is_cuda)

True

In [16]:
## Just making tensors using different methods


In [17]:
## Auto Grad 