In [44]:
print("reck98")

reck98


In [45]:
import torch
import torch.nn as nn


In [46]:
class MyModel(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        
        self.linear = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        
        self.hidden = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        
        x = self.linear(x)
        x = self.relu(x)
        
        x = self.hidden(x)
        x = self.sigmoid(x)
        
        return x

    
        

In [47]:
## make a dataset 

features = torch.rand((100, 5))
labels = torch.rand((100, 1))
print(features.shape)
print(labels.shape)

torch.Size([100, 5])
torch.Size([100, 1])


In [48]:
labels[:5]

tensor([[0.3491],
        [0.4381],
        [0.4253],
        [0.1764],
        [0.7880]])

In [49]:
labels = labels > 0.5
labels = labels.reshape(-1, 1)

In [50]:
## make it float 32
labels = labels.float()
labels[:10]

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [51]:
features.shape[1]

5

In [52]:
model = MyModel(features.shape[1])

In [53]:
model(features)

tensor([[0.5180],
        [0.5482],
        [0.5243],
        [0.5212],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5339],
        [0.5235],
        [0.5180],
        [0.5546],
        [0.5270],
        [0.5409],
        [0.5180],
        [0.5282],
        [0.5180],
        [0.5180],
        [0.5566],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5230],
        [0.5231],
        [0.5393],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5181],
        [0.5180],
        [0.5331],
        [0.5670],
        [0.5271],
        [0.5180],
        [0.5340],
        [0.5180],
        [0.5202],
        [0.5503],
        [0.5342],
        [0.5180],
        [0.5542],
        [0.5211],
        [0.5180],
        [0.5180],
        [0.5180],
        [0.5309],
        [0.5226],
        [0.5180],
        [0.5460],
        [0

In [54]:
from torchinfo import summary

In [55]:
summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [100, 1]                  --
├─Linear: 1-1                            [100, 3]                  18
├─ReLU: 1-2                              [100, 3]                  --
├─Linear: 1-3                            [100, 1]                  4
├─Sigmoid: 1-4                           [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01